get-prhases-service
wolox-training/lf-node pull request #1
Opened 2022-08-29 15:14 UTC by fozzattilucas

## Summary

added a new service to get phrases and a new controller to send the weet to the browser using async/await

## Known Issues

[Change!] List any known issue of the feature you are implementing.

## Trello Card

https://trello.com/c/ZB4lUZYY/32-servicios-promises-witter

2022-08-29 16:40 UTC, elcorren requested changes

2022-08-29 16:40 UTC, elcorren commented on app/services/friki_phrases.js
> +    const data = await axios.get('https://geek-jokes.sameerkumar.website/api?format=json');
Extrayendo la URL como constante en un archivo de constantes podría sumar legibilidad al código, además de tener todas las constantes centralizadas y no tenerlas hardcodeadas 🤔

2022-08-29 16:40 UTC, elcorren commented on app/services/friki_phrases.js
> +    return data.data;
Creo que podrías definir la constante como apiResponse o similar para que el código sea más descriptivo

2022-08-29 16:40 UTC, elcorren commented on app/controllers/weeters.js
> +  res.send(phrase);
No olvides enviar el status de la respuesta

2022-08-29 16:40 UTC, elcorren commented on app/routes.js
>    // app.get('/endpoint/get/path', [], controller.methodGET);
Estas líneas podrías borrarlas si no las utilizas

2022-08-30 13:01 UTC, elcorren commented on app/controllers/weeters.js
> +  res.send(phrase);
En este caso también podrías asignar el status en la misma línea que el send, algo así:
`res.status(200).send(phrase);`

2022-08-30 13:03 UTC, elcorren approved these changes
Excelente Lucas! 🚀

2022-08-30 13:28 UTC, elcorren approved these changes

2022-08-30 13:29 UTC, elcorren approved these changes

2022-08-31 19:30 UTC, jhonjairosepulveda approved these changes

2022-09-01 13:38 UTC, merged