Weet calificate
wolox-training/lf-node pull request #10
Opened 2022-09-29 14:13 UTC by fozzattilucas

## Summary

The functionality to qualify a weet was added and the cases were tested

## Known Issues

[Change!] List any known issue of the feature you are implementing.

## Trello Card

https://trello.com/c/Z0w5249x/37-calificar-weet

2022-09-29 17:51 UTC, elcorren requested changes

2022-09-29 17:51 UTC, elcorren commented on app/controllers/rating.js
> +    const qualify = req.body;
Deberías validar que exista el parámetro "score" en el body y que el rate sea un valor válido (1 o -1)
![image](https://user-images.githubusercontent.com/76002290/193104287-6367cb47-4661-414e-aee6-60b63cfa94ab.png)
![image](https://user-images.githubusercontent.com/76002290/193104060-64a4b6a2-900a-41f4-aa09-b724407419e7.png)

2022-09-29 17:51 UTC, elcorren commented on app/models/raiting.js
> +      score: DataTypes.INTEGER
El modelo acepta cualquier integer para el campo score 🤔

2022-09-29 17:51 UTC, elcorren commented on app/services/rates.js
> +  rating.update({ score: user.score }, { where: { userId: user.userId } }).catch(error => {
también deberías considerar el weetId para evitar que actualice todos los ratings del user indicado 
![image](https://user-images.githubusercontent.com/76002290/193105243-dad72c92-7d9a-4ca2-904e-8af173c68e3f.png)

2022-09-29 17:51 UTC, elcorren commented on test/weetRaiting.test.js
> +'use strict';
Podrías tener en cuenta los casos borde que te indiqué arriba (body sin campos score, score con valor distinto a 1 o -1, actualizar el score de 1 weet existiendo varios weets calificados por el mismo user)

2022-09-29 19:58 UTC, elcorren requested changes

2022-09-29 19:58 UTC, elcorren commented on app/models/raiting.js
> +              next(new Error('Email address already in use!'));
ups 🙃

2022-09-30 21:05 UTC, jhonjairosepulveda approved these changes

2022-10-03 14:00 UTC, merged