Get weets
wolox-training/lf-node pull request #11
Opened 2022-10-03 18:34 UTC by fozzattilucas

## Summary

The functionality to get a weet was added and the cases were tested

## Known Issues

------------------

## Trello Card

https://trello.com/c/kc389W4G/36-obtener-weets

2022-10-03 20:04 UTC, elcorren commented on app/routes.js
> +  app.get('/randomWeet', getWeet);
Este endpoint qué finalidad tiene?

2022-10-03 20:28 UTC, elcorren requested changes

2022-10-03 20:28 UTC, elcorren commented on app/services/weets.js
> +  return weet.create({ content: content.joke, userId }).catch(error => {
content es de tipo string. Este cambio se te habrá pasado al solucionar conflictos

2022-10-03 20:28 UTC, elcorren commented on test/weet.get.test.js
> +    expect(response.body.weets.length).toBe(5);
para evitar "números mágicos" podrías utilizar alguna constante como "defaultLimit". Ayudará a que sea más fácil hacer cambios de ser necesario y también a entender qué significa el valor esperado

2022-10-04 15:42 UTC, jhonjairosepulveda approved these changes

2022-10-04 15:42 UTC, jhonjairosepulveda commented on app/services/weets.js
> +  weet.findAll({ ...pag_params(page, limit), attributes: ['id', 'content', 'userId'] }).catch(error => {
pag_params lo cambiaría a camelCase para conservar el estilo.

2022-10-04 19:29 UTC, elcorren approved these changes

2022-10-04 19:45 UTC, merged