add tests
wolox-training/lf-node pull request #6
Opened 2022-09-19 16:14 UTC by fozzattilucas

## Summary

The functionality was added to list the users as long as they are authenticated and this functionality was tested

## Known Issues

the error persists:
Jest has detected the following 2 open handles potentially keeping Jest from exiting

## Trello Card

https://trello.com/c/zR0OaNoo/3-lista-de-usuarios

2022-09-19 16:49 UTC, elcorren requested changes

2022-09-19 16:49 UTC, elcorren commented on test/users.get.test.js
> +    expect(response.statusCode).toBe(200);
También podrías validar que existiendo X cantidad de usuarios (creados para el test), la consulta devuelva una lista con esa cantidad de usuarios, y qué se espera que devulva en caso de que no se envíen los parámetros de limit o page. De esta forma los tests abarcarían varios casos de prueba 🤔

2022-09-20 17:41 UTC, elcorren approved these changes

2022-09-20 19:39 UTC, merged

2022-10-11 07:35 UTC, fozzattilucas commented
Cierto, ahora lo agrego

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
From: elcorren ***@***.***>
Sent: Monday, September 19, 2022 1:49:39 PM
To: wolox-training/lf-node ***@***.***>
Cc: Fozzatti, Lucas ***@***.***>; Author ***@***.***>
Subject: [External] Re: [wolox-training/lf-node] add tests (PR #6)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________


@elcorren requested changes on this pull request.

________________________________

In test/users.get.test.js<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_wolox-2Dtraining_lf-2Dnode_pull_6-23discussion-5Fr974467807&d=DwMFaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=7kPBR5RdwOGlI-nIHPTQHo6FrY3lY0V4QLI2iWLAAOQ&m=aJe49Dytx8VU5Vre--xgStJ9DAqXRQaUnmP1Qv-sCLI0lsVuil9hSdIWFH1UPAP_&s=3QtZXGGD2AXp0UQBufS1vojJftIVkdTvmQ95AR9Tpm0&e=>:

> @@ -0,0 +1,43 @@
+'use strict';
+const request = require('supertest');
+const jwt = require('jsonwebtoken');
+const app = require('../app');
+const userFactory = require('./factory/userFactory');
+
+describe('POST /users', () => {
+  it('responds with a success status code when data sent meets all the criteria', async () => {
+    const user = await userFactory.create();
+    const token = jwt.sign(user.dataValues.email, process.env.AUTH_SECRET);
+    const response = await request(app)
+      .get('/allusers')
+      .set({ Authorization: token })
+      .query({ limit: 1, page: 1 });
+    expect(response.statusCode).toBe(200);


También podrías validar que existiendo X cantidad de usuarios (creados para el test), la consulta devuelva una lista con esa cantidad de usuarios, y qué se espera que devulva en caso de que no se envíen los parámetros de limit o page. De esta forma los tests abarcarían varios casos de prueba 🤔

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_wolox-2Dtraining_lf-2Dnode_pull_6-23pullrequestreview-2D1112567955&d=DwMFaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=7kPBR5RdwOGlI-nIHPTQHo6FrY3lY0V4QLI2iWLAAOQ&m=aJe49Dytx8VU5Vre--xgStJ9DAqXRQaUnmP1Qv-sCLI0lsVuil9hSdIWFH1UPAP_&s=pVRZyq_dqZbgef5fDr5G5m6er3kKWcs8omJHgu1Hl7E&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_A2SMDJ7OXRKKFTPM7MO25FDV7CKSHANCNFSM6AAAAAAQQIG6IU&d=DwMFaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=7kPBR5RdwOGlI-nIHPTQHo6FrY3lY0V4QLI2iWLAAOQ&m=aJe49Dytx8VU5Vre--xgStJ9DAqXRQaUnmP1Qv-sCLI0lsVuil9hSdIWFH1UPAP_&s=QI866mLFZk48OLbz3sHmQVuR2zxvt5MGM1nRnVAU4wI&e=>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy. Your privacy is important to us. Accenture uses your personal data only in compliance with data protection laws. For further information on how Accenture processes your personal data, please see our privacy statement at https://www.accenture.com/us-en/privacy-policy.
______________________________________________________________________________________

www.accenture.com