User admin
wolox-training/lf-node pull request #7
Opened 2022-09-19 20:52 UTC by fozzattilucas

## Summary

An administrator user was created and granted permissions to create administrator users or update their role, and the case was tested

## Known Issues

[Change!] List any known issue of the feature you are implementing.

## Trello Card

https://trello.com/c/OXD35AqK/16-usuario-administrador

2022-09-21 15:01 UTC, elcorren commented on app/routes.js
> +const { validateRole } = require('./middlewares/validateRole');
Para evitar importar componentes desde cada archivo individual también podés crear un archivo index.js en cada carpeta y dentro de este haces exports de cada archivo individual. De esta forma te quedaría más chica la sección de imports

2022-09-21 17:35 UTC, elcorren commented on config/userObjects.js
> +    role: 'admin'
💡 Para no repetir código también podés generar un objeto "user" con las propiedades básicas y luego generás los distintos users utilizando el spread operator y sobreescribiendo las propiedades que necesitás modificar

2022-09-21 17:45 UTC, elcorren requested changes

2022-09-21 17:45 UTC, elcorren commented on package.json
> +    "jwt-decode": "^3.1.2",
este package añade alguna funcionalidad extra a las que incorpora jwt-simple? 🤔

2022-09-21 17:45 UTC, elcorren commented on app/middlewares/validateRole.js
> +const jwt_decode = require('jwt-decode');
ver comment en el package.json

2022-09-22 12:09 UTC, jhonjairosepulveda commented on app/controllers/users.js
> +        res.status(201).json({ message: success.created });
Acá también puedes emplear las HTTP_CODES de las constantes para que quede uniforme

2022-09-22 20:01 UTC, elcorren requested changes

2022-09-22 20:01 UTC, elcorren commented on test/signup.test.js
> +      .send({ ...objects.succesUser, password: objects.NonWoloxEmail });
quizás la propiedad modificada debería ser email en lugar de password?

2022-09-23 14:21 UTC, elcorren reviewed
muy bien @fozzattilucas , esperemos el approve de @jhonjairosepulveda para mergear 🚀

2022-09-23 15:56 UTC, jhonjairosepulveda approved these changes

2022-09-23 16:01 UTC, merged